In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold, cross_validate
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.inspection import permutation_importance

from sklearn.metrics import (accuracy_score, roc_auc_score, f1_score, precision_score, 
                             recall_score, confusion_matrix, log_loss, RocCurveDisplay,
                             PrecisionRecallDisplay, DetCurveDisplay, ConfusionMatrixDisplay, brier_score_loss)

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import (BaggingClassifier, AdaBoostClassifier, RandomForestClassifier, ExtraTreesClassifier, VotingClassifier)

In [23]:
df = pd.read_csv('https://raw.githubusercontent.com/JamesLo94/schulich_data_science/main/0910/train.csv')

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize,IsAlone,Title
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2,0,Mr
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2,0,Mrs
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1,1,Miss
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2,0,Mrs
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1,1,Mr

In [24]:
df['Sex'] = df['Sex'].astype('category')
df['Embarked'] = df['Embarked'].astype('category')
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
df['IsAlone'] = (df['FamilySize']==1).astype(int)
df['Title'] = (
    df['Name'].str.extract(r",\s*([^.]*)\.", expand = False).
    str.strip()
    .replace({'Mlle':'Miss', 'Ms':'Miss', 'Mme':'Mrs', 'Lady':'Noble', 'Countess':'Noble',
              'Sir':'Noble', "Don":'Noble','Dona':'Noble', 'Jonkheer':'Noble','Dr':'Officer',
              'Col':'Officer','Major':'Officer','Capt':'Officer','Rev':'Officer'}).astype('category')
)

In [25]:
y = df['Survived'].astype(int)
x = df[['Pclass','Sex','Age','SibSp','Parch','Fare','Embarked','FamilySize','IsAlone','Title']]

In [26]:
# separate num / cat columns
num_cols = ['Age','SibSp','Parch','Fare','FamilySize','Pclass']
cat_cols = ['Sex','Embarked','IsAlone','Title']

In [27]:
numeric = Pipeline([('imputer', SimpleImputer(strategy='median')),
                    ['scale', StandardScaler(with_mean=False)]])
categorical = Pipeline([('imputer',SimpleImputer(strategy='most_frequent')),
                        ('onehot', OneHotEncoder(handle_unknown='ignore'))])

prep = ColumnTransformer([('num',numeric, num_cols),('cat',categorical, cat_cols)], sparse_threshold=0.3)

In [28]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)

In [29]:
bag = Pipeline([
    ('prep',prep),
    ('bag',BaggingClassifier(estimator = DecisionTreeClassifier(max_depth=3), n_estimators=200, 
                             max_samples=0.8, bootstrap=True, n_jobs=-1, random_state=42))
])

# 这里estimator使用的model可以换掉，就看需要什么。调参也可以在这里进行

In [30]:
ada = Pipeline([
      ('prep',prep),
      ('clf', AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=2),
                                 n_estimators=300, learning_rate=0.5,random_state=42))
])

In [31]:
rf = Pipeline([
    ('prep',prep),
    ('clf', RandomForestClassifier(n_estimators=400, max_depth=None, random_state=42, n_jobs=-1))
])

et = Pipeline([
    ('prep',prep),
    ('clf', ExtraTreesClassifier(n_estimators=400, max_depth=None, random_state=42, bootstrap=True, n_jobs=-1))
])

vote = Pipeline([
    ('prep',prep),
    ('clf', VotingClassifier(estimators=[
        ('bag',BaggingClassifier(estimator = DecisionTreeClassifier(max_depth=3), n_estimators=200, 
                             max_samples=0.8, bootstrap=True, n_jobs=-1, random_state=42)),
        ('ada',AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=2),
                                 n_estimators=300, learning_rate=0.5,random_state=42)),
        ('rf',RandomForestClassifier(n_estimators=400, max_depth=None, random_state=42, n_jobs=-1)),
        ('et',ExtraTreesClassifier(n_estimators=400, max_depth=None, random_state=42, bootstrap=True, n_jobs=-1))], voting='soft'))
])

In [32]:
models = {'Bagging':bag, 'AdaBoost':ada, 'RandomForest':rf, 'ExtraTrees':et, 'Voting':vote}

In [33]:
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

scoring = {'accuracy':'accuracy', 'roc_auc':'roc_auc', 'f1':'f1', 'precision':'precision', 'recall':'recall', 'neg_log_loss':'neg_log_loss'}

In [ ]:
cv_rows = []

for name, pipe in models.items():
  res = cross_validate(pipe, X_train, y_train, cv=cv, scoring=scoring, n_jobs=-1)
  cv_rows.append({
      'model':name,
      'acc_mean': res['test_accuracy'].mean(),
      'auc_mean': res['test_roc_auc'].mean(),
      'f1_mean': res['test_f1'].mean(),
      'prec_mean': res['test_precision'].mean(),
      'recall_mean': res['test_recall'].mean(),
      'logloss_mean': -res['test_neg_log_loss'].mean()
  })
  
cv_df = pd.DataFrame(cv_rows).sort_values("auc_mean", ascending=False)
cv_df

# logloss_mean要小，才表示预测和实际的差距小。
# 在这个例子里面，Voting和Bagging的效果最好
# RandomForest在这个例子中看起来准确率很高，但可能只是因为数据特性，不是模型准确

,model,acc_mean,auc_mean,f1_mean,prec_mean,recall_mean,logloss_mean
4,Voting,0.813277,0.878642,0.748843,0.775771,0.725253,0.429584
0,Bagging,0.816005,0.870244,0.746214,0.792714,0.706936,0.414278
2,RandomForest,0.797754,0.867506,0.733868,0.740120,0.728889,0.767524
3,ExtraTrees,0.799153,0.863415,0.736214,0.741041,0.732660,0.702860
1,AdaBoost,0.803368,0.846758,0.738679,0.753876,0.725387,0.646987

In [36]:
def per_observation_scoreboard(fitted, X_test, y_test, id_cols=None):
  df = pd.DataFrame(index=X_test.index)
  df['y_true'] = y_test.values

  prob_cols, pred_cols, correct_cols =[], [], []

  for name, model in fitted.items():
    proba = model.predict_proba(X_test)[:,1]
    pred = (proba >= 0.5).astype(int)
    df[f"{name}_proba"] = proba
    df[f"{name}_pred"] = pred
    df[f"{name}_correct"] = (pred == y_test.values).astype(int)

  preds = df[pred_cols].values
  votes = preds.sum(axis=1)
  majority = (votes > (len(pred_cols)/2)).astype(int)
  df['majority_pred'] = majority
  df['majority_correct'] = (df['majority_pred'] == df['y_true']).astype(int)
  
  df['num_models_correct'] = df[correct_cols].sum(axis=1)

  df['unanimous_correct'] = (df['num_models_correct'] == len(correct_cols)).astype(int)
  df['unanimous_wrong'] = (df['num_models_correct'] == 0).astype(int)

  if id_cols:
    df = pd.concat([X_test[id_cols].reset_index(drop=True), df.reset_index(drop=True)], axis=1)
  
  df = df.sort_values(['unanimous_wrong','unanimous_correct', 'num_models_correct'], ascending= [False, True, True])

  return df

In [37]:
test_rows, fitted = [], {}

for name, pipe in models.items():
  pipe.fit(X_train, y_train)
  fitted[name] = pipe
  proba = pipe.predict_proba(X_test)[:,1]
  pred = (proba >= 0.5).astype(int)

  test_rows.append({
      'model':name,
      'accuracy': accuracy_score(y_test, pred),
      'roc_auc': roc_auc_score(y_test, proba),
      'f1': f1_score(y_test, pred),
      'precision': precision_score(y_test, pred),
      'recall': recall_score(y_test, pred),
      'log_loss': log_loss(y_test, proba)
  })
  
test_df = pd.DataFrame(test_rows).sort_values("roc_auc", ascending=False)
test_df

          model  accuracy   roc_auc        f1  precision    recall  log_loss
0       Bagging  0.821229  0.857312  0.750000   0.813559  0.695652  0.426546
4        Voting  0.826816  0.847167  0.763359   0.806452  0.724638  0.459856
3    ExtraTrees  0.821229  0.832279  0.761194   0.784615  0.739130  0.539121
2  RandomForest  0.815642  0.830435  0.755556   0.772727  0.739130  0.543380
1      AdaBoost  0.731844  0.746970  0.647059   0.656716  0.637681  0.668784

In [38]:
scoreboard = per_observation_scoreboard(fitted, X_test, y_test, id_cols=None)

In [39]:
scoreboard

,y_true,Bagging_proba,Bagging_pred,Bagging_correct,AdaBoost_proba,AdaBoost_pred,AdaBoost_correct,RandomForest_proba,RandomForest_pred,RandomForest_correct,...,ExtraTrees_pred,ExtraTrees_correct,Voting_proba,Voting_pred,Voting_correct,majority_pred,majority_correct,num_models_correct,unanimous_correct,unanimous_wrong
565,0,0.127689,0,1,0.492913,0,1,0.157500,0,1,...,0,1,0.210151,0,1,0,1,0.0,1,1
160,0,0.109291,0,1,0.476029,0,1,0.035000,0,1,...,0,1,0.159455,0,1,0,1,0.0,1,1
553,1,0.097014,0,0,0.483462,0,0,0.102500,0,0,...,0,0,0.192619,0,0,0,0,0.0,1,1
860,0,0.115554,0,1,0.480723,0,1,0.012500,0,1,...,0,1,0.157819,0,1,0,1,0.0,1,1
241,1,0.620355,1,1,0.504417,1,1,0.862500,1,1,...,1,1,0.722443,1,1,0,0,0.0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
880,1,0.909191,1,1,0.492372,0,0,0.790000,1,1,...,1,1,0.776641,1,1,0,0,0.0,1,1
91,0,0.100693,0,1,0.493480,0,1,0.002500,0,1,...,0,1,0.150262,0,1,0,1,0.0,1,1
883,0,0.100778,0,1,0.488720,0,1,0.002500,0,1,...,0,1,0.148676,0,1,0,1,0.0,1,1
473,1,0.877843,1,1,0.544272,1,1,0.937500,1,1,...,1,1,0.828654,1,1,0,0,0.0,1,1
637,0,0.238498,0,1,0.501540,1,0,0.149167,0,1,...,0,1,0.249801,0,1,0,1,0.0,1,1

In [41]:
df.iloc[553]

PassengerId                                  554
Survived                                       1
Pclass                                         3
Name           Leeni, Mr. Fahim ("Philip Zenni")
Sex                                         male
Age                                         22.0
SibSp                                          0
Parch                                          0
Ticket                                      2620
Fare                                       7.225
Cabin                                        NaN
Embarked                                       C
FamilySize                                     1
IsAlone                                        1
Title                                         Mr
Name: 553, dtype: object